sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (pymysql.err.IntegrityError) (1048, "Column 'nick_name' cannot be null") [SQL: 'INSERT INTO players (uid, nick_name, avatar, sex, imei, imsi, mac, model, reg_time, channel_id, platform, ver, diamond, token, refresh_token, expires_at, auto_token, openid, unionid, agent, phone, pwd, verify_code, verify_expire_at, login_time, ip, share_time, get_diamond, refer_uid, refer_time, withdraw_time, withdraw_nickname, bind_after_login_time, level) VALUES (%(uid)s, %(nick_name)s, %(avatar)s, %(sex)s, %(imei)s, %(imsi)s, %(mac)s, %(model)s, %(reg_time)s, %(channel_id)s, %(platform)s, %(ver)s, %(diamond)s, %(token)s, %(refresh_token)s, %(expires_at)s, %(auto_token)s, %(openid)s, %(unionid)s, %(agent)s, %(phone)s, %(pwd)s, %(verify_code)s, %(verify_expire_at)s, %(login_time)s, %(ip)s, %(share_time)s, %(get_diamond)s, %(refer_uid)s, %(refer_time)s, %(withdraw_time)s, %(withdraw_nickname)s, %(bind_after_login_time)s, %(level)s)'] [parameters: {'uid': 0, 'nick_name': None, 'avatar': 'http://thirdwx.qlogo.cn/mmopen/PiajxSqBRaELJc8pdeb7o2TicjSYfs6wvhKLXMusojxbug8ibMKKFaS32564lJhexkoc6MWu73Cvnn38xW6XSGzZw/132', 'sex': 1, 'imei': None, 'imsi': None, 'mac': None, 'model': None, 'reg_time': 1524729380, 'channel_id': 5, 'platform': 1, 'ver': None, 'diamond': 5, 'token': None, 'refresh_token': None, 'expires_at': None, 'auto_token': None, 'openid': 'o7JLT1QUu4QU9COHvjTlgCXb8kTY', 'unionid': 'o-6LUvlgBexcmU0TY4Fk7an0ZWG0', 'agent': None, 'phone': None, 'pwd': None, 'verify_code': None, 'verify_expire_at': None, 'login_time': None, 'ip': None, 'share_time': None, 'get_diamond': None, 'refer_uid': None, 'refer_time': None, 'withdraw_time': None, 'withdraw_nickname': None, 'bind_after_login_time': None, 'level': None}] (Background on this error at: http://sqlalche.me/e/gkpj)